Modify: 모든 기능 구현을 위한 파일 수정 완료
wecode-bootcamp-korea/react-exercises pull request #22
Opened 2020-08-11 07:03 UTC by recurian1058

wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 파일수정을 통한 기능 구현 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- map함수를 이용한 component 반복 사용
- 라이프 사이클과 fetch함수를 이용한 API주소호출
- setState함수와 이벤트 객체를 이용한 인자 넘겨주기
- filter메소드를 활용한 특정 정보만 노출
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 으악

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-11 11:20 UTC, jamessoun93 requested changes
수고하셨습니다!

전반적으로 로직 및 구현사항 전부 완벽하지만, 코드 스타일에 수정이 필요해 보입니다.
전반적으로 줄바꿈, 메서드 간 간격, 등을 조정해주셨으면 좋겠습니다!

2020-08-11 11:20 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/recurian1058/Components/CardList/CardList.js
> +    return <div className="card-list">{this.props.monsters.map((monster) => <Card id={monster.id} name={monster.name} email={monster.email} />)}</div>;
가독성을 위해 줄바꿈 적용해주세요!

2020-08-11 11:20 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/recurian1058/Monsters.js
> +  }
👍 👍 👍

2020-08-11 11:20 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/recurian1058/Monsters.js
> +  }
👍 👍 👍

2020-08-11 11:20 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/recurian1058/Monsters.js
> +    let monstersNameFilter = this.state.monsters.filter(monster => monster.name.toLowerCase().includes(this.state.userInput.toLowerCase()))
완벽!

2020-08-11 12:02 UTC, recurian1058 commented on src/Assignments/Monsters/students/11th/recurian1058/Components/CardList/CardList.js
> +    return <div className="card-list">{this.props.monsters.map((monster) => <Card id={monster.id} name={monster.name} email={monster.email} />)}</div>;
class와 render사이에 한줄 띄우라는 말씀이시죠??

2020-08-12 03:40 UTC, recurian1058 commented on src/Assignments/Monsters/students/11th/recurian1058/Components/CardList/CardList.js
> +    return <div className="card-list">{this.props.monsters.map((monster) => <Card id={monster.id} name={monster.name} email={monster.email} />)}</div>;
수정 완료하였습니다

2020-08-12 07:18 UTC, jamessoun93 commented
LGTM 🙇🏻‍♂️ 

수고하셨습니다!!

2020-08-12 07:18 UTC, merged