[이호현] Add: Monsters.js, CardList.js, Card.js 작업
wecode-bootcamp-korea/react-exercises pull request #24
Opened 2020-08-11 10:53 UTC by LeeHoHyun-hemtory

wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Monsters.js, CardList.js, Card.js 처음 commit 입니다
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Monsters.js: fetch기능 추가
- Monsters.js: 이벤트 핸들러 추가
- Monsters.js: SearchBox filter 기능 추가
- CardList.js: Card map method 기능 추가
- Card.js: props 값 사용

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-11 11:51 UTC, jamessoun93 requested changes
리뷰내용 확인해주세요!

2020-08-11 11:51 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/LeeHoHyun-hemtory/Components/Card/Card.js
> +        <p>{this.props.email}</p>
👍 👍 👍

2020-08-11 11:51 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/LeeHoHyun-hemtory/Components/CardList/CardList.js
> +        return <Card key={mon.id} id={mon.id} name={mon.name} email={mon.email}/>
중괄호와 return 문은 생략할 수 있겠죠? 😇

2020-08-11 11:51 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/LeeHoHyun-hemtory/Monsters.js
> +  }
👍👍👍

2020-08-11 11:51 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/LeeHoHyun-hemtory/Monsters.js
> +    });
필터링 로직 좋습니다! 하지만 이 부분도 단순 리턴문이기 때문에 중괄호와 return 키워드를 생략할 수 있겠죠?

2020-08-11 11:51 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/LeeHoHyun-hemtory/Monsters.js
> +    });
그리고 temp 보다는 조금 더 명확한 변수명을 사용해주셨으면 좋겠습니다!

2020-08-11 14:46 UTC, LeeHoHyun-hemtory commented on src/Assignments/Monsters/students/11th/LeeHoHyun-hemtory/Components/CardList/CardList.js
> +        return <Card key={mon.id} id={mon.id} name={mon.name} email={mon.email}/>
Card component에 빨간줄 그어지길래 return이 빠져서 그런가했는데
( )로 묶어주고 { } 생략하니까 잘 적용되네요
수정하겠습니다

2020-08-11 14:46 UTC, LeeHoHyun-hemtory commented on src/Assignments/Monsters/students/11th/LeeHoHyun-hemtory/Monsters.js
> +    });
수정하겠습니다

2020-08-12 07:24 UTC, jamessoun93 commented
수고하셨습니다!

LGTM! 🙇🏻‍♂️

2020-08-12 07:25 UTC, merged