[손수민] Add: Monsters.js, CardList.js, Card.js 작업
wecode-bootcamp-korea/react-exercises pull request #26
Opened 2020-08-11 13:23 UTC by codeamor

## 수정 사항 간략한 한줄 요약
Monsters 과제 입니다.
		 
## 수정 사항들 자세한 내용

1. fetch를 이용한 데이터 로딩

2. SearchBox 에 Input 값으로 setState

3. 필터링 로직 구현

## 기타 질문 및 특이 사항
항상 감사합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-12 07:43 UTC, jamessoun93 requested changes
review 반영해서 다시 push 해주세요!

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/10th/limo-sum/Components/CardList/CardList.js
>          })}
남 코드 건드시면 아니됩니다ㅠㅠ!!
제가 다시 돌려놓을게요~

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/codeamor/Components/Card/Card.js
> +        <p>{this.props.email}</p>
Gooood 😄

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/codeamor/Components/CardList/CardList.js
> +    console.log(this.props.monsters);
구조분해할당 너무 잘 적용하셨습니다!
아래 콘솔로그로 확인하는 부분도 너무 좋네요!

다만, 콘솔로그는 개발단계에서 확인하는 코드이니, push 전에는 꼭 지워주세요~ 😇
그리고 이미 monsters 배열을 destructuring 을 통해 분해할당하였으니, 콘솔로그에서도 monsters 만 써서 확인할 수 있었겠네요!

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/codeamor/Components/CardList/CardList.js
> +    console.log(this.props.monsters);
콘솔로그만 빼주세요~

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/codeamor/Components/CardList/CardList.js
> +        })}
깔끔합니다! 

문제가 되는 부분은 아니지만, 가독성을 위해 element 를 monster 라는 단어로 대체해주시는게 좋지 않을까 싶습니다. monsters 배열 내의 요소로 있는 객체들이 전부 monster 하나의 정보를 담고 있는 객체이기 때문에요!

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/codeamor/Monsters.js
> +    userInput: "", // 데이터를 받기 위해 스트링 초기화
주석으로 설명 좋네요 👍

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/codeamor/Monsters.js
> +    fetch(`https://jsonplaceholder.typicode.com/users`)
여기는 JS 변수를 사용할 것이 아니기 때문에 template literal 대신 단순 string 으로 두셔도 무방합니다.

2020-08-12 07:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/codeamor/Monsters.js
> +    );
필터링 로직에서 `monster.name` 의 소문자 버전과 `userInput` 을 그대로 비교한다면, 정확한 비교가 힘듭니다. `userInput` 도 소문자형태로 변경해서 비교해주셔야 더욱 더 정확한 비교가 될 수 있습니다!

2020-08-13 10:14 UTC, codeamor commented on src/Assignments/Monsters/students/10th/limo-sum/Components/CardList/CardList.js
>          })}
헉.. 제껀줄 알고 건드렸나봅니다..
감사합니다!!

2020-08-13 10:18 UTC, codeamor commented on src/Assignments/Monsters/students/11th/codeamor/Components/CardList/CardList.js
> +    console.log(this.props.monsters);
넵! 수정했습니다

2020-08-13 10:18 UTC, codeamor commented on src/Assignments/Monsters/students/11th/codeamor/Components/CardList/CardList.js
> +        })}
넵! 수정했습니다

2020-08-13 10:18 UTC, codeamor commented on src/Assignments/Monsters/students/11th/codeamor/Monsters.js
> +    userInput: "", // 데이터를 받기 위해 스트링 초기화
감사합니다!

2020-08-13 10:18 UTC, codeamor commented on src/Assignments/Monsters/students/11th/codeamor/Monsters.js
> +    fetch(`https://jsonplaceholder.typicode.com/users`)
헛 넵! 감사합니다

2020-08-13 10:21 UTC, codeamor commented on src/Assignments/Monsters/students/11th/codeamor/Monsters.js
> +    );
리뷰 감사합니다!! 추가했습니다

2020-08-13 10:56 UTC, merged