[이영섭] Add: Task1~Task4 구현 완료
wecode-bootcamp-korea/react-exercises pull request #27
Opened 2020-08-11 15:28 UTC by seobie

wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Task1부터 Task4까지 구현
		 
## 수정 사항들 자세한 내용
- Task1 API 호출 구현
- Task2 API 호출의 결과값 `props`로 자식에게 전달
  - API 호출 후 저장한 배열을 자식 컴포넌트인 CardList.js에 `props`를
활용하여 넘겨줌
  - 넘겨준 데이터를 CardList.js 에서 `console.log`로 확인
- Task3 map()사용
  - 넘겨받은 배열을 기준으로 map함수를 활용하여 Card.js 컴포넌트를 리턴
  - Card.js에 `id`, `name`, `email`을 `props`로 넘겨줌
- Task4 `props` 활용
  - Card.js 컴포넌트 모양 및 구조 구현

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-12 07:54 UTC, jamessoun93 requested changes
리뷰 반영해주세요!

2020-08-12 07:54 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seobie/Components/Card/Card.js
> +        <p>{this.props.dataFromCardList.email}</p>
👍👍👍

2020-08-12 07:54 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seobie/Components/CardList/CardList.js
> +  componentDidMount() {}
하는 일이 없는 메소드는 지워주세요!

2020-08-12 07:54 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seobie/Components/CardList/CardList.js
> +    console.log(this.props.monsters);
콘솔로그 활용해서 props 로 전달받은 데이터 확인하는 부분 너무 좋습니다! 😉
하지만 콘솔로그 문은 개발단계에서 확인용으로 사용하는 것이기 때문에, push 전에는 꼭 지워주세요~!

2020-08-12 07:54 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seobie/Monsters.js
> +    console.log("componentDidMount");
여기도 마찬가지입니다!!

2020-08-12 07:54 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seobie/Monsters.js
> +  };
setState 직후에 console.log 로 업데이트 된 state 값을 확인하면 제대로 된 결과값이 나오지 않을텐데요!
왜 그런지 알고 계실까요?! 답변 달아주세요!

2020-08-12 13:32 UTC, seobie commented on src/Assignments/Monsters/students/11th/seobie/Monsters.js
> +  };
비동기 문제라서 `render` 밑에 찍고 확인해야 하는거로 알고 있습니다!

2020-08-13 08:43 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seobie/Monsters.js
> +  };
정확해요!! 🥳

2020-08-13 08:47 UTC, jamessoun93 commented
LGTM!

수고하셨습니다 🤠

2020-08-13 08:48 UTC, merged