[이효정] Add: monsters 구현완료
wecode-bootcamp-korea/react-exercises pull request #29
Opened 2020-08-12 05:32 UTC by ovovv

wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- monsters 과제 요구사항 구현 완료
		 
## 수정 사항들 자세한 내용
- API주소 호출 완료.
- API 호출의 결과값을 props를 이용하여 자식 컨포넌트에 전달 완료.
- handleChange 메소드를 이용한 이벤트 활성화 완료.
- filter 메소드를 활용한 필터링로직 구현 완료.

## 기타 질문 및 특이 사항
- filter를 좀 더 연습해야할 것 같습니다...;-;

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-12 08:06 UTC, jamessoun93 requested changes
몇 가지 review 사항 반영해서 push 해주세요~

2020-08-12 08:06 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/ovovv/Components/Card/Card.js
> +        <p>{this.props.email}</p>
완벽합니다! 🤠

2020-08-12 08:06 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/ovovv/Components/CardList/CardList.js
> +      })}
👍👍👍

2020-08-12 08:06 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/ovovv/Components/SearchBox/SearchBox.js
> +        onChange={this.props.hendleChange}
일부러 스펠링을 바꿔보신건가요?! 🤔

2020-08-12 08:06 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/ovovv/Monsters.js
> +    filter: [],
`monsters` 배열에서 `filter()` 함수의 결과값을 저장하고 싶은 용도셨다면, `filter` 라는 이름보다 `filteredList` 혹은 `filteredMonsters` 처럼 누가봐도 알기 쉬운 key 로 지어주시는게 좋습니다!

2020-08-12 08:06 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/ovovv/Monsters.js
> +  }
`handleChange` 메소드에서 한번에 필터링 로직까지 처리해서 `setState` 해주시는 방식 잘 응용하셨습니다 💯

2020-08-12 08:06 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/ovovv/Monsters.js
> +    console.log(this.state);
콘솔로그로 업데이트 된 state 객체 확인하는 부분 너무 좋네요!

다만, 콘솔로그문은 개발단계 확인용이기 때문에 push 할때는 꼭 없애주세요~ 🙃

2020-08-13 04:25 UTC, ovovv commented on src/Assignments/Monsters/students/11th/ovovv/Components/SearchBox/SearchBox.js
> +        onChange={this.props.hendleChange}
아뇨 오타입니다.ㅎ.ㅎ.ㅎ.ㅎ.ㅎㅎㅎ 수정하겟습니다!

2020-08-13 04:35 UTC, ovovv commented on src/Assignments/Monsters/students/11th/ovovv/Monsters.js
> +    filter: [],
해당 부분 filteredList으로 수정하겠습니다! 피드백 정말 감사합니다!! :)

2020-08-13 04:37 UTC, ovovv commented on src/Assignments/Monsters/students/11th/ovovv/Monsters.js
> +    console.log(this.state);
앗 이부분 확인 후 지운다는걸 잊었네요 ;-; 수정하도록 하겠습니다!

2020-08-13 05:03 UTC, ovovv commented
리뷰부분 수정완료하였습니다! 확인 부탁드립니다! 👍

2020-08-13 10:11 UTC, jamessoun93 commented
LGTM 🥳

수고하셨습니다 💯 💯 💯

2020-08-13 10:11 UTC, merged