[김건우]Add: Monsters 과제(기능구현)
wecode-bootcamp-korea/react-exercises pull request #30
Opened 2020-08-12 07:57 UTC by kgwoo

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Monsters 기능 구현

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- jsonplaceholder의 API호출
- Card에 props로 id name email 전달
- map()사용하여, card를 cardlist에 배열만큼 전달
- filter() 사용하여, monsters 객체의 name과 input창의 value 값을 비교하여 일치하는 것을 띄워줌
		 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-12 07:58 UTC, kgwoo commented
> ## 수정 사항 간략한 한줄 요약
> (여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
> 
> * Monsters 기능 구현
> 
> ## 수정 사항들 자세한 내용
> (여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
> 
> * jsonplaceholder의 API호출
> * Card에 props로 id name email 전달
> * map()사용하여, card를 cardlist에 배열만큼 전달
> * filter() 사용하여, monsters 객체의 name과 input창의 value 값을 비교하여 일치하는 것을 띄워줌
> 
> ## 기타 질문 및 특이 사항
> (궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
> 
> ## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
> * [x]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
> * [x]  Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
> * [x]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
> * [ ]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-12 08:09 UTC, jamessoun93 requested changes
전반적으로 너무 좋습니다!

코멘트 확인해서 요청사항 반영해서 다시 push 해주세요!

2020-08-12 08:09 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/kgwoo/Components/Card/Card.js
> +        <p>{this.props.email}</p>
Goood 😎

2020-08-12 08:09 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/kgwoo/Components/CardList/CardList.js
> +    </div>
`map()` 함수 사용 잘하셨네요! 🤩

2020-08-12 08:09 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/kgwoo/Monsters.js
> +    })
👏👏👏

2020-08-12 08:09 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/kgwoo/Monsters.js
> +        <CardList  monsters={result}></CardList>
React 에서는 JSX tag 내에 자식 요소 혹은 text 가 없다면 self-closing tag 를 활용하여 해당 태그를 닫아줄 수 있죠? 

수정해주세요!

2020-08-13 10:11 UTC, jamessoun93 commented
LGTM! 수고하셨습니다! 🙇🏻‍♂️

2020-08-13 10:12 UTC, merged

2020-08-13 11:56 UTC, kgwoo commented
> LGTM! 수고하셨습니다! 🙇🏻‍♂️
감사합니다!!