Add: react monster 과제 완료
wecode-bootcamp-korea/react-exercises pull request #32
Opened 2020-08-12 13:56 UTC by seungha-oh

## 수정 사항 간략한 한줄 요약
react monster 과제 완료
		 
## 수정 사항들 자세한 내용
- api 호출하여 데이터 로딩
- api 호출 결과값을 자식 컴포넌트에 전달
- map 사용하여 특정 값을 가진 컴포넌트 생성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-13 10:42 UTC, jamessoun93 requested changes
승하님 전체적으로 너무 깔끔해서 보는 내내 기분이 좋았어요 🥳 🥳 🥳 

몇가지 리뷰사항만 반영해서 새로 push 해주세요!!

2020-08-13 10:42 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seungha-oh/Components/Card/Card.js
> +        <p>{this.props.email}</p>
좋습니다 좋아요 😎

2020-08-13 10:42 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seungha-oh/Components/CardList/CardList.js
> +  }
state 로 관리하고 싶은 데이터가 없다면 해당 constructor 전체가 불필요합니다! 😇

2020-08-13 10:42 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seungha-oh/Components/CardList/CardList.js
> +          return <Card key={id} id={el.id} name={el.name} email={el.email} />;
`map()` 너무 잘쓰셨네요 👍 👍 👍

2020-08-13 10:42 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seungha-oh/Components/SearchBox/SearchBox.js
> +import "../../Monsters";
음.. 이걸 여기에 넣으신 이유가 있을까요? 🤔

2020-08-13 10:42 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seungha-oh/Monsters.js
> +      .then((res) => this.setState({ monsters: res, filteredMonsters: res }));
fetch 함수 사용 완벽합니다 👍 👍

2020-08-13 10:42 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seungha-oh/Monsters.js
> +  };
아까 저랑 같이 한 부분이죠? ㅎㅎ 꼭 기억하고 계셔야 합니다! 🙇🏻‍♂️

2020-08-13 10:42 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/seungha-oh/Monsters.js
> +        <CardList monsters={this.state.filteredMonsters} />
👍 👍 👍

2020-08-13 14:53 UTC, seungha-oh commented on src/Assignments/Monsters/students/11th/seungha-oh/Components/CardList/CardList.js
> +  }
삭제하였습니다.

2020-08-13 14:55 UTC, seungha-oh commented on src/Assignments/Monsters/students/11th/seungha-oh/Components/SearchBox/SearchBox.js
> +import "../../Monsters";
이유없이 들어가 있는 것 같습니다. 삭제했습니다!

2020-08-14 05:05 UTC, jamessoun93 commented
LGTM!

수고하셨습니다~ 😎

2020-08-14 05:05 UTC, merged