[이상훈]Add: Monster과제 필수구현사항 완료
wecode-bootcamp-korea/react-exercises pull request #33
Opened 2020-08-13 04:22 UTC by sanghunlee-711

wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 필수구현사항 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- componentDidMount() 를 이용해 데이터 로딩을 처리
- fetch() 를 이용해 실제 API를 GET 메소드로 호출
- map()을 이용해 컴포넌트를 재사용
- filter()를 이용해 검색 기능

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-13 11:18 UTC, jamessoun93 requested changes
상훈님! 리뷰반영해서 push 해주세요 😎

2020-08-13 11:18 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Components/Card/Card.js
> +        <p>{this.props.email}</p>
props 로 필요한 데이터 너무 잘 받아가지고 오셨네요 🤠

하지만 `id`, `name`, `email` 은 해당 `img` 태그에 불필요한 요소이므로 빼주시는게 좋습니다!

2020-08-13 11:18 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Components/CardList/CardList.js
> +    )
`map()` 함수 사용도 완벽하고, destructuring 까지 goood 입니다! 👍 👍 👍 

다만 원활한 협업과, 가독성을 위해 일관되고 깔끔한 코드 스타일을 유지해주시는게 좋습니다! 아래처럼요!
```suggestion
    <div className="card-list">
          {this.props.monsters.map(({ id, name, email }) => <Card id={id} name={name} email={email} /> )}
    </div>
    )
```

2020-08-13 11:18 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +      .then(response => this.setState({monsters : response}, this.monsterFilter));
fetch 함수 로직 너무 좋네요!

다만, `componentDidMount` 에서 setState 후 필터링 로직을 담당하는 `this.monsterFilter` 함수를 실행하는 것 보다, userInput 을 감지하는 `handleChange` 함수에서만 필터링 로직을 실행시켜주면 더 좋을 것 같네요 😎

2020-08-13 11:18 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +  }
`handleChange` 와 `monsterFilter` 함수를 따로 두고 각각 `setState` 를 하는 것 보다, `handleChange` 에서 `e.target.value` 로 필터링을 처리하면 한번에 `setState` 할 수 있게 됩니다!

고민해보시고 수정해주세요 🙇🏻‍♂️

2020-08-13 11:18 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +    console.log("IN MONSTERS",this.state.monsterFiltering)
콘솔로그 문으로 업데이트 된 state 값 확인하는 부분 너무 좋습니다 😉

하지만 콘솔로그 문은 개발단계 확인용으로만 사용하시고, push 하기 전에는 꼭 지우고 올려주세요!

2020-08-13 11:18 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +        <CardList monsters={this.state.monsterFiltering} />
👍 👍 👍

2020-08-13 13:01 UTC, sanghunlee-711 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Components/Card/Card.js
> +        <p>{this.props.email}</p>
넵 제외했습니다😎

2020-08-13 13:03 UTC, sanghunlee-711 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Components/CardList/CardList.js
> +    )
앞으로 작성하면서 유념해보겠습니다 :)

2020-08-13 13:07 UTC, sanghunlee-711 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +      .then(response => this.setState({monsters : response}, this.monsterFilter));
감사합니다 :) 다시보니 fetch 에서 한번 handleChange에서 한번 실행을 시켰네요 😅 수정했습니다!

2020-08-13 13:15 UTC, sanghunlee-711 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +  }
아래 처럼 수정 전 후로 변경 하였는데, 혹시 더 직관적인 방법이 있으시면 알려주시면 감사하겠습니다! 🙏


1. 수정 전
```
  handleChange = (e) => {
    this.setState({userInput: e.target.value}, this.monsterFilter);
  }
  
  monsterFilter = () => {
    this.setState({monsterFiltering : this.state.monsters.filter(({name}) => name.toLowerCase().includes(this.state.userInput))});
  }
```

2. 수정 후
```
  handleChange = (e) => {
    this.setState({userInput: e.target.value});
    this.setState({monsterFiltering : this.state.monsters.filter(({name}) => name.toLowerCase().includes(e.target.value))})
  }
```

2020-08-13 13:16 UTC, sanghunlee-711 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +    console.log("IN MONSTERS",this.state.monsterFiltering)
넵 !! 😸

2020-08-13 15:11 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +  }
@sanghunlee-711 

와우 👍👍👍
조금만 변경하면 더 효율적으로 바꿀 수 있습니다ㅎㅎ

`setState`를 따로따로 연달아 두번 부르기 보다는, 아래처럼 한번의 `setState` 호출에 두개의 프로퍼티를 변경할 수 있습니다. 
(더욱 더 정확한 비교를 위해 `e.target.value` 에도 `toLowerCase()` 를 추가했습니다)
``` js
handleChange = (e) => {
  this.setState({ userInput: e.target.value, monsterFiltering: this.state.monsters.filter(({name}) => name.toLowerCase().includes(e.target.value.toLowerCase()))});
}
```

2020-08-14 04:12 UTC, sanghunlee-711 commented on src/Assignments/Monsters/students/11th/sanghunlee-711/Monsters.js
> +  }
오... 짱입니다.. 앞으로 setState 더 유용하게 잘 써먹어보겠습니다 🎃

2020-08-14 05:06 UTC, jamessoun93 commented
리뷰 반영하시느라 수고하셨습니다!

LGTM 🥳🥳🥳

2020-08-14 05:07 UTC, merged

2020-08-15 02:32 UTC, sanghunlee-711 commented
> 리뷰 반영하시느라 수고하셨습니다!
> 
> LGTM 🥳🥳🥳

SGTM 🎧🎧🎧🎧🎧