[이도윤] Add: Monster 과제 필수구현사항 완료
wecode-bootcamp-korea/react-exercises pull request #34
Opened 2020-08-13 08:12 UTC by doyoonear

## 수정 사항 간략한 한줄 요약
- react monster 과제 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- fetch 함수 사용한 API 호출, 데이터 사용.
- onChange 를 사용한 event 구현 
- map 을 사용하여 자식 컴포넌트에 데이터 전달.

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-13 11:29 UTC, jamessoun93 requested changes
전체적으로 너무 깔끔하고 좋네요 도윤님!! 🙃

아주 짜잘한 반영사항만 확인 후 새로 push 해주시면 LGTM!!!

2020-08-13 11:29 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/doyoonear/Components/Card/Card.js
> +        <p>{this.props.mons.email}</p>
굳굳굳! 😊

2020-08-13 11:29 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/doyoonear/Components/CardList/CardList.js
> +    </div>;
map 함수 잘 사용해주셨네요 💯

2020-08-13 11:29 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +    .then(res => this.setState({monsters: res}))
fetch 함수 사용도 잘해주셨네요 👍 

하지만, fetch 함수의 then 문을 사용할때는 꼭 indentation 을 추가해주세요!
```suggestion
    fetch('https://jsonplaceholder.typicode.com/users')
      .then(res => res.json())
      .then(res => this.setState({monsters: res}))
```

2020-08-13 11:29 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +  }
`onChange` 이벤트 사용 완벽합니다 😎

2020-08-13 11:29 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +    const filtered = this.state.monsters.filter(el => el.name.toLowerCase().includes(this.state.userInput.toLowerCase()));
필터링 로직 또한 완벽합니다!

2020-08-13 11:29 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +          mons1={this.state.monsters}
잘해주셨는데 `mons1` 보다는 조금 더 알기 쉬운 이름으로 변경해주시면 더 좋을 것 같네요 😉

2020-08-14 05:44 UTC, doyoonear commented on src/Assignments/Monsters/students/11th/doyoonear/Components/Card/Card.js
> +        <p>{this.props.mons.email}</p>
감사합니당~ 😃

2020-08-14 05:44 UTC, doyoonear commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +    .then(res => this.setState({monsters: res}))
수정했습니다!

2020-08-14 05:44 UTC, doyoonear commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +  }
감사합니당~ 😃

2020-08-14 05:45 UTC, doyoonear commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +          mons1={this.state.monsters}
변경했습니다!

2020-08-14 05:45 UTC, doyoonear commented on src/Assignments/Monsters/students/11th/doyoonear/Monsters.js
> +    const filtered = this.state.monsters.filter(el => el.name.toLowerCase().includes(this.state.userInput.toLowerCase()));
😆

2020-08-14 05:46 UTC, doyoonear commented on src/Assignments/Monsters/students/11th/doyoonear/Components/CardList/CardList.js
> +    </div>;
감사합니다.. map.. 어려워요.. 🥺

2020-08-20 02:30 UTC, merged