[송다슬] Add: Monster 과제 필수구현사항 완료
wecode-bootcamp-korea/react-exercises pull request #35
Opened 2020-08-14 05:02 UTC by aleatorik

wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Taks 1 해결 : API 호출 
- Task 2 해결 : API 호출의 결과값 props 로 자식에게 전달
- Task 3 해결 : map() 사용
- Task 4 해결 : props 활용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- componentDidMount(), fetch(), setState() 활용하여 API 호출
- API 호출에 따른 배열 값을 부모(Monsters.js) 컴포넌트에서 자식(CardList.js) 컴포넌트로 이동
- map()함수를 이용하여 부모 컴포넌트의 props(id, name, email)를 갖는 Card.js 컴포넌트를 리턴
- props(id) 객체를 통해 카드마다 다른 이미지를 출력

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
map 함수를 쓸 때 어느 순서로 코드를 작성하면 좋을지 알고 싶습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-20 02:34 UTC, jamessoun93 requested changes
전체적으로 너무 깔끔하고 기능구현도 완벽하게 해주셨네요! 🥳 🥳 🥳 
중간에 한가지 수정사항 요청드린 부분만 반영해주신 후 push 해주세요~

2020-08-20 02:34 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/daseulsongme/Components/Card/Card.js
> +        <p>{this.props.email}</p>
👍 👍 👍

2020-08-20 02:34 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/daseulsongme/Components/CardList/CardList.js
> +  };
`CardList` 컴포넌트에서 이 state 객체가 담아야할 데이터가 있어서 만들어주신걸까요?
아무일도 하지 않는 불필요한 state 객체는 없애주세요!

2020-08-20 02:34 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/daseulsongme/Components/CardList/CardList.js
> +        ))}
너무 잘하셨습니다! 🥳

2020-08-20 02:34 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/daseulsongme/Monsters.js
> +  }
완벽하네요! 🤠

2020-08-20 02:34 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/daseulsongme/Monsters.js
> +  };
이 부분도 너무 잘 적용해주셨네요!

2020-08-20 02:34 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/daseulsongme/Monsters.js
> +    );
필터함수도 완벽합니다.. 😅

2020-08-20 02:34 UTC, jamessoun93 commented on src/Assignments/Monsters/students/11th/daseulsongme/Monsters.js
> +        <CardList monsters={filterMonster} />
굳!!

2020-08-21 05:48 UTC, aleatorik commented on src/Assignments/Monsters/students/11th/daseulsongme/Components/CardList/CardList.js
> +  };
state 객체 삭제 완료하였습니다!

2020-08-29 12:52 UTC, merged